-- Good Food — the whole schema, as it stood on Supabase in September 2026.
--
-- Runs once on a fresh database (src/lib/migrate.js). Later changes go into
-- new numbered files next to this one.
--
-- Ids are identity columns "by default", so imported rows keep their ids and
-- the import moves the counters past them. Constraint names match the ones
-- the API recognises in its error messages (users_chat_id_key …).

create table companies (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz default now(),
  company_name    text,
  company_code    text constraint companies_company_code_key unique,
  access          boolean default true,
  phone           text,
  code_version    integer not null default 1,
  code_rotated_at timestamptz
);

comment on column companies.code_version is
  'Bumped every time the code is reissued. Users stamped with an older version must re-enter the code.';

create table users (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz not null default now(),
  last_login        timestamptz,
  user_name         text,
  access            boolean default true,
  role              text,
  chat_id           bigint constraint users_chat_id_key unique,
  tg_username       text,
  notice_message_id bigint,
  company_id        bigint references companies (id) on delete set null,
  code_version      integer
);

comment on column users.code_version is
  'The companies.code_version this user last entered a code for. Below the company''s current value = stale.';

create table categories (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz default now(),
  category_name text,
  image_path    text
);

create table materials (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz default now(),
  material_name text,
  cost          bigint,
  unit          text not null default 'pcs'
                constraint materials_unit_check check (unit in ('pcs', 'kg'))
);

create table items (
  id                 bigint generated by default as identity primary key,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz default now(),
  item_name          text,
  item_category      text,
  item_cost          bigint,
  materials          jsonb,
  image_path         text,
  available          boolean not null default true,
  frontpad_id        text constraint items_frontpad_id_key unique,
  frontpad_return_id text constraint items_frontpad_return_id_key unique
);

create table reminders (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz default now(),
  name        text not null,
  days        smallint[] not null,
  time_of_day text not null default '09:00',
  text        text not null,
  audience    jsonb not null,
  enabled     boolean not null default true,
  last_run_at timestamptz
);

create table orders (
  id                    bigint generated by default as identity primary key,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz default now(),
  company_id            bigint references companies (id) on delete set null,
  user_id               bigint references users (id) on delete set null,
  kind                  text not null default 'order',
  status                text not null default 'new',
  items                 jsonb not null,
  total                 bigint default 0,
  comment               text,
  decided_at            timestamptz,
  notice_message_id     bigint,
  edited_at             timestamptz,
  service_date          date,
  source_order_id       bigint references orders (id) on delete set null,
  frontpad_status       text not null default 'none',
  frontpad_order_id     text,
  frontpad_order_number text,
  frontpad_error        text,
  frontpad_sent_at      timestamptz
);

comment on column orders.service_date is
  'The day the order counts for. Same day, or the next one when it arrived after the cutoff.';

create table broadcasts (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  sent_by      bigint references users (id) on delete set null,
  sent_by_name text,
  text         text,
  image_path   text,
  audience     jsonb not null,
  status       text not null default 'sending',
  recipients   integer not null default 0,
  delivered    integer not null default 0,
  failed       integer not null default 0,
  finished_at  timestamptz,
  deleted_at   timestamptz,
  reminder_id  bigint references reminders (id) on delete set null
);

create table broadcast_targets (
  id           bigint generated by default as identity primary key,
  broadcast_id bigint not null references broadcasts (id) on delete cascade,
  user_id      bigint references users (id) on delete set null,
  user_name    text,
  company_id   bigint references companies (id) on delete set null,
  chat_id      bigint,
  message_id   bigint,
  status       text not null default 'pending',
  error        text,
  deleted_at   timestamptz
);

-- One row per reminder per day: the unique key is the claim on the day.
create table reminder_runs (
  id            bigint generated by default as identity primary key,
  reminder_id   bigint not null references reminders (id) on delete cascade,
  run_on        date not null,
  scheduled_at  text not null,
  reminder_name text,
  status        text not null default 'pending',
  attempts      integer not null default 1,
  broadcast_id  bigint references broadcasts (id) on delete set null,
  recipients    integer not null default 0,
  delivered     integer not null default 0,
  failed        integer not null default 0,
  error         text,
  started_at    timestamptz not null default now(),
  finished_at   timestamptz,
  constraint reminder_runs_reminder_id_run_on_key unique (reminder_id, run_on)
);

create table frontpad_log (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  order_id    bigint references orders (id) on delete set null,
  action      text not null,
  simulated   boolean not null default false,
  ok          boolean not null default false,
  request     jsonb,
  http_status integer,
  response    text,
  error       text
);

create table app_settings (
  key        text primary key,
  value      jsonb not null,
  updated_at timestamptz not null default now()
);

create table admin_prefs (
  admin_key  text primary key,
  prefs      jsonb not null,
  updated_at timestamptz not null default now()
);

create index users_company_id_idx              on users (company_id);
create index orders_company_created_idx        on orders (company_id, created_at desc);
create index orders_created_at_idx             on orders (created_at desc);
create index orders_service_date_idx           on orders (service_date);
create index orders_source_order_id_idx        on orders (source_order_id);
create index broadcast_targets_broadcast_id_idx on broadcast_targets (broadcast_id);
create index frontpad_log_created_at_idx       on frontpad_log (created_at desc);
